using System.Security.AccessControl;
using System.Security.Principal;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
namespace AgentOS.Core;
internal static class WorkExecution
{
 internal static Func<HyperVProfile,SdkGuestRequest,CancellationToken,Task<SdkGuestResult>> Runner=(p,r,c)=>new HyperVSdkRunner(p).RunAsync(r,c);
 internal static Func<HyperVProfile,HyperVProbe> Availability=p=>{var probe=HyperVExecution.Probe(p with{DestinationCredentialTarget=null},false);return !probe.Available?probe:ServiceRunning("vmms")&&ServiceRunning("vmcompute")?probe:new(false,"Hyper-V VM services unavailable.");};
 [System.Runtime.InteropServices.StructLayout(System.Runtime.InteropServices.LayoutKind.Sequential)]private struct ServiceStatus{public uint Type,State,Controls,ExitCode,Specific,Check,Wait;}
 [System.Runtime.InteropServices.DllImport("advapi32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode)]private static extern IntPtr OpenSCManager(string? machine,string? database,uint access);
 [System.Runtime.InteropServices.DllImport("advapi32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode)]private static extern IntPtr OpenService(IntPtr manager,string name,uint access);
 [System.Runtime.InteropServices.DllImport("advapi32.dll")]private static extern bool QueryServiceStatus(IntPtr service,out ServiceStatus status);
 [System.Runtime.InteropServices.DllImport("advapi32.dll")]private static extern bool CloseServiceHandle(IntPtr handle);
 static bool ServiceRunning(string name){if(!OperatingSystem.IsWindows())return false;var manager=OpenSCManager(null,null,1);if(manager==IntPtr.Zero)return false;try{var service=OpenService(manager,name,4);if(service==IntPtr.Zero)return false;try{return QueryServiceStatus(service,out var status)&&status.State==4;}finally{CloseServiceHandle(service);}}finally{CloseServiceHandle(manager);}}
 internal static HyperVProbe DescribeAvailability(HyperVProfile p){var probe=Availability(p);if(!probe.Available)return probe;if(!WorkerReady(p))return new(false,"Separate nonadministrator SDK worker credential unavailable.");return probe;}
 internal static Func<HyperVProfile,bool> WorkerReady=h=>!string.IsNullOrWhiteSpace(h.WorkerCredentialTarget)&&HyperVCredential.Read(h.WorkerCredentialTarget,out var worker,out _)&&HyperVCredential.Read(h.GuestCredentialTarget,out var admin,out _)&&!worker.Equals(admin,StringComparison.OrdinalIgnoreCase);
 internal static string Hash(string s)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(s)));
 internal static (string Snapshot,string Hash) Capture(string root){var p=new ExecutionProfileRegistry(root).Current;EnsureAvailable(p);var s=JsonSerializer.Serialize(p);return(s,Hash(s));}
 internal static ExecutionProfile Profile(WorkUnit w){if(string.IsNullOrEmpty(w.ExecutionProfileSnapshot))return new();if(Hash(w.ExecutionProfileSnapshot)!=w.ExecutionProfileSha256)throw new InvalidDataException("Frozen execution profile hash mismatch.");var p=JsonSerializer.Deserialize<ExecutionProfile>(w.ExecutionProfileSnapshot)??throw new InvalidDataException("Frozen profile missing.");ExecutionProfileRegistry.Validate(p);return p;}
 internal static ExecutionBackend Backend(WorkUnit w)=>Profile(w).SdkBackend;
 internal static void EnsureAvailable(WorkUnit w)=>EnsureAvailable(Profile(w));
 static void EnsureAvailable(ExecutionProfile p){ExecutionProfileRegistry.Validate(p);if(p.SdkBackend==ExecutionBackend.AppContainer)return;if(p.SdkBackend!=ExecutionBackend.HyperV||p.HyperV is not {} h)throw new NotSupportedException("Selected SDK backend unavailable: exact shutdown proof missing.");var probe=Availability(h);if(!probe.Available)throw new NotSupportedException("Hyper-V SDK unavailable: "+probe.Reason);if(!File.Exists(h.BaseVhdPath)||StateStore.HashFile(h.BaseVhdPath)!=h.BaseVhdSha256.ToUpperInvariant())throw new InvalidDataException("Base VHD SHA-256 mismatch.");if(!WorkerReady(h))throw new NotSupportedException("Separate nonadministrator SDK worker credential unavailable.");}
 internal static bool ShutdownConfirmed(SdkGuestResult r)=>r.ShutdownConfirmed&&(r.State is WindowsVmState.Completed or WindowsVmState.Failed);
 internal static string Receipt(SdkGuestResult r){var s=JsonSerializer.Serialize(r);if(Encoding.UTF8.GetByteCount(s)>65536)throw new InvalidDataException("SDK receipt too large.");return s;}
 internal static (int ExitCode,bool ShutdownConfirmed,string Receipt,string EnvironmentSha256,bool SourceUnchanged) ValidationResult(SdkGuestResult r,string input,string command,string profile){var state=(r.State==WindowsVmState.Completed&&r.ExitCode==0)||(r.State==WindowsVmState.Failed&&r.ExitCode is {} failed&&failed!=0);var ok=ShutdownConfirmed(r)&&state&&r.TrustedCollector&&r.InputSha256==input&&r.PostSourceSha256==input&&r.CommandSha256==command&&r.ProfileSha256==profile&&r.EnvironmentFingerprint.Length==64&&r.ReceiptSha256.Length==64&&r.OwnerReceiptSha256.Length==64&&r.EffectSha256.Length==64;return(ok?r.ExitCode??125:125,ShutdownConfirmed(r),Receipt(r),r.EnvironmentFingerprint,ok);}
 internal static IReadOnlyList<string> InputManifest(string root)
 {
  var files=Directory.EnumerateFiles(root,"*",SearchOption.AllDirectories).Where(f=>!Path.GetRelativePath(root,f).Split(Path.DirectorySeparatorChar).Any(x=>x.Equals(".git",StringComparison.OrdinalIgnoreCase)||x.Equals("auth.json",StringComparison.OrdinalIgnoreCase))).Select(f=>Path.GetRelativePath(root,f).Replace('\\','/')).OrderBy(x=>x,StringComparer.Ordinal).ToArray();
  foreach(var path in files)if(path.Split('/').Any(x=>x is "" or "." or ".."))throw new IOException("SDK input path unsafe.");return files;
 }
 internal static string SourceHash(string root,IReadOnlyList<string>? inputPaths=null)
 {
  var paths=inputPaths??InputManifest(root);var lines=new List<string>();foreach(var p in paths){var file=Path.Combine(root,p.Replace('/',Path.DirectorySeparatorChar));if(!File.Exists(file)||(File.GetAttributes(file)&FileAttributes.ReparsePoint)!=0)throw new IOException("SDK input changed or linked.");lines.Add(p+":"+StateStore.HashFile(file));}return Hash(string.Join("\n",lines));
 }
 internal static bool TrustedRunResult(SdkGuestResult r,string input,string command,string profile)=>ShutdownConfirmed(r)&&r.TrustedCollector&&((r.State==WindowsVmState.Completed&&r.ExitCode==0)||(r.State==WindowsVmState.Failed&&r.ExitCode is {} failed&&failed!=0))&&r.InputSha256==input&&r.CommandSha256==command&&r.ProfileSha256==profile&&r.PostSourceSha256.Length==64&&r.EnvironmentFingerprint.Length==64&&r.ReceiptSha256.Length==64&&r.OwnerReceiptSha256.Length==64&&r.EffectSha256.Length==64;
 private static string OwnerRoot(string root){var data=Path.GetFullPath(root);if(File.GetAttributes(data).HasFlag(FileAttributes.ReparsePoint))throw new IOException("SDK data root is a link.");var runs=Path.Combine(data,"sdk-runs");Directory.CreateDirectory(runs);if(File.GetAttributes(runs).HasFlag(FileAttributes.ReparsePoint))throw new IOException("SDK owner root is a link.");return runs;}
 private static void ProtectOwnerDirectory(string path)
 {
  if(!OperatingSystem.IsWindows())return;if(File.GetAttributes(path).HasFlag(FileAttributes.ReparsePoint))throw new IOException("SDK owner directory is a link.");using var identity=WindowsIdentity.GetCurrent();var user=identity.User??throw new UnauthorizedAccessException("SDK owner identity unavailable.");var acl=new DirectorySecurity();acl.SetAccessRuleProtection(true,false);acl.SetOwner(user);foreach(var sid in new[]{user,new SecurityIdentifier(WellKnownSidType.LocalSystemSid,null)})acl.AddAccessRule(new FileSystemAccessRule(sid,FileSystemRights.FullControl,InheritanceFlags.ContainerInherit|InheritanceFlags.ObjectInherit,PropagationFlags.None,AccessControlType.Allow));new DirectoryInfo(path).SetAccessControl(acl);VerifyOwnerDirectory(path);
 }
 internal static void VerifyOwnerDirectory(string path)
 {
  if(!OperatingSystem.IsWindows())return;if(File.GetAttributes(path).HasFlag(FileAttributes.ReparsePoint))throw new IOException("SDK owner directory is a link.");using var identity=WindowsIdentity.GetCurrent();var user=identity.User??throw new UnauthorizedAccessException("SDK owner identity unavailable.");var acl=new DirectoryInfo(path).GetAccessControl(AccessControlSections.Access|AccessControlSections.Owner);var owner=acl.GetOwner(typeof(SecurityIdentifier))??throw new UnauthorizedAccessException("SDK owner unavailable.");if(!acl.AreAccessRulesProtected||!owner.Equals(user))throw new UnauthorizedAccessException("SDK owner ACL is not protected for the current user.");var system=new SecurityIdentifier(WellKnownSidType.LocalSystemSid,null);foreach(FileSystemAccessRule rule in acl.GetAccessRules(true,false,typeof(SecurityIdentifier)))if(rule.IdentityReference is not SecurityIdentifier sid||(!sid.Equals(user)&&!sid.Equals(system))||rule.AccessControlType!=AccessControlType.Allow)throw new UnauthorizedAccessException("SDK owner ACL grants another principal.");
 }
 internal static bool HasUnknownOwnership(string root,string id){var owner=Path.Combine(OwnerRoot(root),id);if(Directory.Exists(owner)&&File.GetAttributes(owner).HasFlag(FileAttributes.ReparsePoint))return true;return File.Exists(Path.Combine(owner,"active.json"))||File.Exists(Path.Combine(owner,"unknown.json"));}
 internal static void ReconcileOwnership(string root){var p=OwnerRoot(root);foreach(var d in Directory.EnumerateDirectories(p)){if(!File.Exists(Path.Combine(d,"active.json")))continue;try{VerifyOwnerDirectory(d);}catch{continue;}if(!File.Exists(Path.Combine(d,"unknown.json")))File.WriteAllText(Path.Combine(d,"unknown.json"),"Exact VM shutdown unproven after restart.");}}
 static string Artifact(string p){p=HyperVSdkRunner.SafeRelative(p);if(p.Split('/').Any(x=>x.StartsWith('.')||x.Equals("auth.json",StringComparison.OrdinalIgnoreCase)||x.Equals("config.toml",StringComparison.OrdinalIgnoreCase)))throw new ArgumentException("Metadata/config artifact forbidden.");return p;}
 static void Copy(string from,string to,ref int count,ref long bytes)
 {
  foreach(var e in Directory.EnumerateFileSystemEntries(from)){var n=Path.GetFileName(e);if(n.Equals(".git",StringComparison.OrdinalIgnoreCase)||n.Equals("auth.json",StringComparison.OrdinalIgnoreCase))continue;if(File.GetAttributes(e).HasFlag(FileAttributes.ReparsePoint))throw new IOException("SDK source link forbidden.");var d=Path.Combine(to,n);if(Directory.Exists(e)){Directory.CreateDirectory(d);Copy(e,d,ref count,ref bytes);}else{count++;bytes+=new FileInfo(e).Length;if(count>4096||bytes>16*1024*1024)throw new ArgumentException("SDK source exceeds bounds.");File.Copy(e,d);}}
 }
 static void Export(string stage,string workspace,IEnumerable<string> paths)
 {
  foreach(var p in paths){var source=Path.Combine(stage,p.Replace('/',Path.DirectorySeparatorChar));if(!File.Exists(source))continue;for(var c=source;c.StartsWith(stage+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase);c=Path.GetDirectoryName(c)!)if(File.GetAttributes(c).HasFlag(FileAttributes.ReparsePoint))throw new IOException("Artifact link forbidden.");var target=Path.Combine(workspace,p.Replace('/',Path.DirectorySeparatorChar));for(var c=Path.GetDirectoryName(target)!;c.StartsWith(workspace,StringComparison.OrdinalIgnoreCase);c=Path.GetDirectoryName(c)!){if(Directory.Exists(c)&&File.GetAttributes(c).HasFlag(FileAttributes.ReparsePoint))throw new IOException("Destination link forbidden.");if(c.Equals(workspace,StringComparison.OrdinalIgnoreCase))break;}Directory.CreateDirectory(Path.GetDirectoryName(target)!);if(File.Exists(target)&&File.GetAttributes(target).HasFlag(FileAttributes.ReparsePoint))throw new IOException("Destination link forbidden.");var temp=target+".agentos-"+Guid.NewGuid().ToString("N");try{File.Copy(source,temp);File.Move(temp,target,true);}finally{if(File.Exists(temp))File.Delete(temp);}}
 }
 internal static async Task<SdkGuestResult> RunSdkAsync(WorkUnit w,string root,string script,IReadOnlyList<string> artifacts,int seconds,CancellationToken ct)
 {
  if(!Guid.TryParseExact(w.Id,"N",out _))throw new ArgumentException("Invalid work identity.");
  if(!Path.GetFullPath(w.Workspace).StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new UnauthorizedAccessException("SDK source must be an owned private workspace.");
  if(Backend(w)!=ExecutionBackend.HyperV)throw new NotSupportedException("agent_os_sdk requires selected Hyper-V profile.");EnsureAvailable(w);
  if(string.IsNullOrWhiteSpace(script)||script.Length>8192||seconds is <1 or >300||artifacts.Count>32)throw new ArgumentException("SDK request exceeds bounds.");
  var paths=artifacts.Select(Artifact).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();var owner=Path.Combine(OwnerRoot(root),w.Id);Directory.CreateDirectory(owner);if(File.GetAttributes(owner).HasFlag(FileAttributes.ReparsePoint))throw new IOException("SDK owner directory is a link.");if(HasUnknownOwnership(root,w.Id))throw new IOException("Prior VM shutdown unproven.");ProtectOwnerDirectory(owner);
  var stage=Path.Combine(owner,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(stage);WindowsVmExecution.ValidateTree(w.Workspace);int count=0;long bytes=0;Copy(w.Workspace,stage,ref count,ref bytes);
  var inputs=InputManifest(stage);var inputHash=SourceHash(stage,inputs);var commandHash=Hash(script);var profileHash=Hash(JsonSerializer.Serialize(Profile(w).HyperV));var operationId=Path.GetFileName(stage);var active=Path.Combine(owner,"active.json");
  await File.WriteAllTextAsync(active,JsonSerializer.Serialize(new{Work=w.Id,Profile=w.ExecutionProfileSha256,Stage=stage,OperationId=operationId,Inputs=inputs}),CancellationToken.None);
  try
  {
   var r=(await Runner(Profile(w).HyperV!,new SdkGuestRequest(script,stage,paths,seconds),ct)) with{OperationId=operationId};
   var receipt=Receipt(r);var file=Path.Combine(owner,"receipt-"+Guid.NewGuid().ToString("N")+".json");await File.WriteAllTextAsync(file,receipt,CancellationToken.None);await File.WriteAllTextAsync(file+".sha256",Hash(receipt),CancellationToken.None);
   var proven=TrustedRunResult(r,inputHash,commandHash,profileHash);if(r.State==WindowsVmState.Completed&&proven){WindowsVmExecution.ValidateTree(stage);WindowsVmExecution.ValidateTree(w.Workspace);Export(stage,w.Workspace,paths);}
   if(proven)File.Delete(active);else await File.WriteAllTextAsync(Path.Combine(owner,"unknown.json"),receipt,CancellationToken.None);return r;
  }
  catch{await File.WriteAllTextAsync(Path.Combine(owner,"unknown.json"),"Runner failed; shutdown unproven.",CancellationToken.None);throw;}
 }
 internal static Func<HyperVProfile,string,CancellationToken,Task<SdkGuestResult>> Recoverer=(p,d,c)=>new HyperVSdkRunner(p).RecoverOwnedAsync(d,c);
 internal static string? PendingOperationId(string root,string id){var active=Path.Combine(OwnerRoot(root),id,"active.json");if(!File.Exists(active))return null;VerifyOwnerDirectory(Path.GetDirectoryName(active)!);using var doc=JsonDocument.Parse(File.ReadAllText(active));return doc.RootElement.GetProperty("OperationId").GetString();}
 private static void ExportRecovered(SdkManifest m,string stage,string workspace)
 {
  using var doc=JsonDocument.Parse(File.ReadAllText(m.Result));var artifacts=doc.RootElement.GetProperty("Artifacts");long total=0;var paths=new List<string>();WindowsVmExecution.ValidateTree(stage);WindowsVmExecution.ValidateTree(workspace);
  foreach(var item in artifacts.EnumerateObject()){var relative=Artifact(item.Name);if(!m.Artifacts.Contains(relative,StringComparer.OrdinalIgnoreCase))throw new InvalidDataException("Unrequested recovered artifact.");var bytes=Convert.FromBase64String(item.Value.GetString()??"");total+=bytes.Length;if(total>1_000_000)throw new InvalidDataException("Recovered artifact bound exceeded.");var target=Path.GetFullPath(Path.Combine(stage,relative.Replace('/',Path.DirectorySeparatorChar)));if(!target.StartsWith(Path.GetFullPath(stage)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("Recovered artifact escaped stage.");Directory.CreateDirectory(Path.GetDirectoryName(target)!);File.WriteAllBytes(target,bytes);paths.Add(relative);}
  WindowsVmExecution.ValidateTree(stage);Export(stage,workspace,paths);
 }
 internal static async Task<SdkGuestResult> ReconcileAsync(WorkUnit w,string root,string operationId,CancellationToken ct)
 {
  if(!Guid.TryParseExact(operationId,"N",out _))throw new ArgumentException("Exact SDK operation ID required.");if(!Path.GetFullPath(w.Workspace).StartsWith(Path.GetFullPath(root)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase))throw new UnauthorizedAccessException("SDK destination must be an owned private workspace.");if(Backend(w)!=ExecutionBackend.HyperV)throw new NotSupportedException("Work did not select Hyper-V SDK.");EnsureAvailable(w);
  var owner=Path.Combine(OwnerRoot(root),w.Id);VerifyOwnerDirectory(owner);var active=Path.Combine(owner,"active.json");if(!File.Exists(active))throw new IOException("No persisted SDK VM ownership record.");using var record=JsonDocument.Parse(File.ReadAllText(active));var a=record.RootElement;
  if(a.GetProperty("Work").GetString()!=w.Id||a.GetProperty("Profile").GetString()!=w.ExecutionProfileSha256||a.GetProperty("OperationId").GetString()!=operationId)throw new InvalidDataException("SDK owner identity or frozen profile changed.");
  var stage=Path.GetFullPath(a.GetProperty("Stage").GetString()??"");if(!stage.Equals(Path.GetFullPath(Path.Combine(owner,operationId)),StringComparison.OrdinalIgnoreCase))throw new InvalidDataException("SDK stage escaped exact operation.");
  var inputPaths=a.GetProperty("Inputs").EnumerateArray().Select(x=>x.GetString()??"").ToArray();var sidecars=Path.Combine(stage,".git","agent-os-temp");if(!Directory.Exists(sidecars))throw new IOException("SDK VM owner sidecar unavailable.");var owned=Directory.EnumerateDirectories(sidecars).Where(d=>File.Exists(Path.Combine(d,"manifest.json"))&&File.Exists(Path.Combine(d,"owner.json"))).ToArray();if(owned.Length!=1)throw new IOException("Exact SDK VM ownership is ambiguous or missing.");WindowsVmExecution.ValidateTree(stage);
  var m=JsonSerializer.Deserialize<SdkManifest>(File.ReadAllText(Path.Combine(owned[0],"manifest.json")))??throw new InvalidDataException("SDK manifest invalid.");using var ownerRecord=JsonDocument.Parse(File.ReadAllText(Path.Combine(owned[0],"owner.json")));var o=ownerRecord.RootElement;
  if(o.GetProperty("Nonce").GetString()!=m.Nonce||o.GetProperty("Name").GetString()!=m.VmName||o.GetProperty("Disk").GetString()!=m.Disk||o.GetProperty("Creator").GetString()!=m.Creator||!o.TryGetProperty("VmId",out var vmIdElement)||vmIdElement.GetGuid()==Guid.Empty)throw new InvalidDataException("Exact SDK VM owner record changed.");
  if(Path.GetFullPath(m.Result)!=Path.GetFullPath(Path.Combine(owned[0],"result.json"))||Path.GetFullPath(m.Confirmed)!=Path.GetFullPath(Path.Combine(owned[0],"shutdown-confirmed")))throw new InvalidDataException("SDK owner receipt path changed.");
  if(m.CollectorVersion!="agentos-sdk-collector-v2"||m.Base!=Profile(w).HyperV!.BaseVhdPath||m.BaseHash!=Profile(w).HyperV!.BaseVhdSha256||m.InputSha256!=SourceHash(stage,inputPaths)||m.CommandSha256!=Hash(m.Script)||m.ProfileSha256!=Hash(JsonSerializer.Serialize(Profile(w).HyperV)))throw new InvalidDataException("SDK owner evidence mismatches frozen inputs.");
  var r=(await Recoverer(Profile(w).HyperV!,owned[0],ct)) with{OperationId=operationId};var receipt=Receipt(r);var file=Path.Combine(owner,"reconciled-"+operationId+"-"+Guid.NewGuid().ToString("N")+".json");await File.WriteAllTextAsync(file,receipt,CancellationToken.None);await File.WriteAllTextAsync(file+".sha256",Hash(receipt),CancellationToken.None);
  var actualReceiptHash=File.Exists(m.Result)?StateStore.HashFile(m.Result):"";var expectedOwnerHash=Hash(m.Nonce+"\n"+m.VmName+"\n"+vmIdElement.GetGuid().ToString("D")+"\n"+m.Disk+"\n"+actualReceiptHash);string effectHash="";if(File.Exists(m.Result)){using var effectDoc=JsonDocument.Parse(File.ReadAllText(m.Result));effectHash=Hash(effectDoc.RootElement.GetProperty("Artifacts").GetRawText());}
  if(!ShutdownConfirmed(r)||!((r.State==WindowsVmState.Completed&&r.ExitCode==0)||(r.State==WindowsVmState.Failed&&r.ExitCode is {} failed&&failed!=0))||!r.TrustedCollector||r.InputSha256!=m.InputSha256||r.CommandSha256!=m.CommandSha256||r.ProfileSha256!=m.ProfileSha256||r.EnvironmentFingerprint.Length!=64||r.ReceiptSha256!=actualReceiptHash||r.OwnerReceiptSha256!=expectedOwnerHash||r.EffectSha256!=effectHash)return r;
  if(r.State==WindowsVmState.Completed)ExportRecovered(m,stage,w.Workspace);File.Move(active,Path.Combine(owner,"resolved-"+operationId+".json"),true);var unknown=Path.Combine(owner,"unknown.json");if(File.Exists(unknown))File.Move(unknown,Path.Combine(owner,"unknown-"+operationId+".json"),true);return r;
 }
}
