using AgentOS.Core;
using System.Net;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
namespace AgentOS.Tests;
public static partial class ExternalDeliveryChecks
{
 static void Check(bool x,string m){if(!x)throw new Exception(m);}
 sealed class Credential:IScopedCredentialProvider{public string? GetSecret(string t)=>t is "AgentOS/GitHub/api.github.com/acme/repo" or "AgentOS/Deployment/deploy.example"?"fixture":null;}
 sealed class Handler(Func<HttpRequestMessage,HttpResponseMessage> reply):HttpMessageHandler{protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage q,CancellationToken ct){var r=reply(q);r.RequestMessage??=q;return Task.FromResult(r);}}
 static HttpResponseMessage Json(HttpStatusCode c,object o)=>new(c){Content=new StringContent(JsonSerializer.Serialize(o),Encoding.UTF8,"application/json")};
 static string Sha(string t,byte[] b)=>Convert.ToHexString(SHA1.HashData(Encoding.ASCII.GetBytes(t+" "+b.Length+"\0").Concat(b).ToArray())).ToLowerInvariant();
 static GitObjectSnapshot Snapshot(){var b=Encoding.UTF8.GetBytes("approved\n");var bs=Sha("blob",b);var tree=Encoding.UTF8.GetBytes("100644 file.txt\0").Concat(Convert.FromHexString(bs)).ToArray();var ts=Sha("tree",tree);var parent=new string('b',40);var raw="tree "+ts+"\nparent "+parent+"\nauthor A <a@example.com> 1767225600 +0000\ncommitter A <a@example.com> 1767225600 +0000\n\nreviewed\n";var cs=Sha("commit",Encoding.UTF8.GetBytes(raw));return new(new(cs,ts,[parent],"reviewed\n","A","a@example.com","2026-01-01T00:00:00+00:00","A","a@example.com","2026-01-01T00:00:00+00:00"),[new(bs,"blob",Convert.ToBase64String(b),null),new(ts,"tree",null,[new("file.txt","100644","blob",bs)])]);}
 static EffectScope Scope(GitObjectSnapshot snap,string op="branch",string? title=null,string? baseSha=null)=>new("github",snap.Commit.Sha,new string('B',64),new string('C',64),new string('D',64),new string('E',64),"https://api.github.com/acme/repo",op,JsonSerializer.Serialize(new GitHubEffect("https://api.github.com","acme","repo","agent/review",snap.Commit.Sha,null,"main",title,"",snap,baseSha)));
 static void BinarySnapshotCheck(){var data=new byte[]{0,255,10,128,0,42};var b=Sha("blob",data);var tree=Encoding.UTF8.GetBytes("100644 bytes.bin\0").Concat(Convert.FromHexString(b)).ToArray();var t=Sha("tree",tree);var parent=new string('b',40);var raw="tree "+t+"\nparent "+parent+"\nauthor A <a@example.com> 1767225600 +0000\ncommitter A <a@example.com> 1767225600 +0000\n\nbinary\n";var c=Sha("commit",Encoding.UTF8.GetBytes(raw));new GitObjectSnapshot(new(c,t,[parent],"binary\n","A","a@example.com","2026-01-01T00:00:00+00:00","A","a@example.com","2026-01-01T00:00:00+00:00"),[new(b,"blob",Convert.ToBase64String(data),null),new(t,"tree",null,[new("bytes.bin","100644","blob",b)])]).Validate(c);}
 public static async Task RunAsync(){BinarySnapshotCheck();PostgreSqlMigrationGuard.Validate("CREATE TABLE approved.items (id integer DEFAULT 'COMMIT'); -- ROLLBACK\n","approved");PostgreSqlMigrationGuard.Validate("CREATE TABLE approved.items (id text DEFAULT $$COMMIT$$);","approved");foreach(var sql in new[]{"COMMIT; CREATE TABLE approved.items(id int);","CREATE TABLE approved.items(id int); ROLLBACK;","CREATE TABLE other.items(id int);","CREATE EXTENSION dblink;","CREATE TABLE approved.items(id int DEFAULT dblink_connect('x'));"}){try{PostgreSqlMigrationGuard.Validate(sql,"approved");throw new Exception("Unsafe SQL accepted: "+sql);}catch(InvalidDataException){}}await GitAsync();await DatabaseDeliveryAsync();await ReceiptsAsync();}
 static async Task GitAsync(){var snap=Snapshot();snap.Validate(snap.Commit.Sha);try{(snap with{Commit=snap.Commit with{Message="changed"}}).Validate(snap.Commit.Sha);throw new Exception("Changed commit encoding accepted");}catch(InvalidDataException){}var calls=new List<string>();bool branch=false,commit=false,wrong=false,lost=false;
  var handler=new Handler(q=>{var p=q.RequestUri!.AbsolutePath;calls.Add(q.Method+" "+p);if(p.Contains("/git/ref/heads/"))return branch?Json(HttpStatusCode.OK,new{@object=new{sha=snap.Commit.Sha}}):Json(HttpStatusCode.NotFound,new{});if(q.Method==HttpMethod.Get&&p.Contains("/git/commits/"))return p.EndsWith(snap.Commit.Parents[0])?Json(HttpStatusCode.OK,new{sha=snap.Commit.Parents[0]}):commit?Json(HttpStatusCode.OK,new{sha=snap.Commit.Sha,tree=new{sha=snap.Commit.Tree},parents=snap.Commit.Parents.Select(sha=>new{sha})}):Json(HttpStatusCode.NotFound,new{});if(q.Method==HttpMethod.Get)return Json(HttpStatusCode.NotFound,new{});if(p.EndsWith("/git/blobs"))return Json(HttpStatusCode.Created,new{sha=wrong?new string('f',40):snap.Objects[0].Sha});if(p.EndsWith("/git/trees"))return Json(HttpStatusCode.Created,new{sha=snap.Objects[1].Sha});if(p.EndsWith("/git/commits")){commit=true;return Json(HttpStatusCode.Created,new{sha=snap.Commit.Sha});}if(p.EndsWith("/git/refs")){branch=true;if(lost)throw new IOException("response lost");return Json(HttpStatusCode.Created,new{});}throw new Exception(p);});
  var root=Path.Combine(Path.GetTempPath(),"agentos-delivery-"+Guid.NewGuid().ToString("N"));try{var journal=new EffectIntentJournal(root);var adapter=new GitHubEffects(journal,new Credential(),handler);var one=await adapter.PrepareAsync("one",Scope(snap));Check((await adapter.ExecuteAsync("one")).State==ExternalEffectState.Prepared&&calls.Count==0,"HTTP before approval");journal.Approve("one",one.Scope.Digest,"reviewer");Check((await adapter.ExecuteAsync("one")).State==ExternalEffectState.Completed,"Git upload failed");Check(calls.FindIndex(x=>x.EndsWith("/git/blobs"))<calls.FindIndex(x=>x.EndsWith("/git/trees"))&&calls.FindIndex(x=>x.EndsWith("/git/trees"))<calls.FindIndex(x=>x.EndsWith("/git/commits"))&&calls.FindIndex(x=>x.EndsWith("/git/commits"))<calls.FindIndex(x=>x.EndsWith("/git/refs")),"Upload order");branch=false;commit=false;wrong=true;calls.Clear();var bad=await adapter.PrepareAsync("bad",Scope(snap));journal.Approve("bad",bad.Scope.Digest,"reviewer");Check((await adapter.ExecuteAsync("bad")).State==ExternalEffectState.Unknown&&!calls.Any(x=>x.EndsWith("/git/refs")),"Wrong SHA published");wrong=false;lost=true;branch=false;commit=false;calls.Clear();var li=await adapter.PrepareAsync("lost",Scope(snap));journal.Approve("lost",li.Scope.Digest,"reviewer");Check((await adapter.ExecuteAsync("lost")).State==ExternalEffectState.Unknown,"Lost response confirmed");Check((await adapter.ReconcileAsync("lost")).State==ExternalEffectState.Completed&&calls.Count(x=>x.EndsWith("/git/refs"))==1,"Blind retry");}finally{if(Directory.Exists(root))Directory.Delete(root,true);}await PullRaceAsync(snap);}
 static async Task PullRaceAsync(GitObjectSnapshot snap){var root=Path.Combine(Path.GetTempPath(),"agentos-pr-"+Guid.NewGuid().ToString("N"));try{var posts=0;var handler=new Handler(q=>{if(q.Method==HttpMethod.Post){posts++;return Json(HttpStatusCode.Created,new{});}if(q.RequestUri!.AbsolutePath.EndsWith("/git/ref/heads/main"))return Json(HttpStatusCode.OK,new{@object=new{sha=new string('d',40)}});return Json(HttpStatusCode.OK,new{@object=new{sha=snap.Commit.Sha}});});var journal=new EffectIntentJournal(root);var adapter=new GitHubEffects(journal,new Credential(),handler);var intent=await adapter.PrepareAsync("pr",Scope(snap,"pull_request","Review",new string('c',40)));journal.Approve("pr",intent.Scope.Digest,"reviewer");Check((await adapter.ExecuteAsync("pr")).State==ExternalEffectState.Stale&&posts==0,"Base race posted");}finally{if(Directory.Exists(root))Directory.Delete(root,true);}}
 sealed class FakeExecutor: IIsolatedDeploymentExecutor{public int Runs;public DeploymentCapability Capability=>new("hyperv","vm","https://deploy.example",true);public Task<EffectOutcome> ExecuteAsync(string id,DeploymentEffect effect,CancellationToken ct){Runs++;return Task.FromResult(new EffectOutcome(ExternalEffectState.Completed,"guest exit zero"));}public Task<EffectOutcome> ReconcileAsync(string id,DeploymentEffect effect,CancellationToken ct)=>throw new Exception("VM reconciliation should not prove remote application");}
 static async Task ReceiptsAsync(){var c=new DeploymentReceiptContract("https://deploy.example/receipts","AgentOS/Deployment/deploy.example",["203.0.113.10"]);var e=new DeploymentEffect("hyperv",new string('A',64),new string('B',64),new string('C',64),"https://deploy.example",c);var scope=new EffectScope("deployment",new string('a',40),new string('D',64),e.ArtifactSha256,e.CommandSha256,e.EnvironmentSha256,e.Destination,"deploy",JsonSerializer.Serialize(e));var receipt=new DeploymentAppliedReceipt("one",scope.Digest,scope.EvidenceSha256,e.ArtifactSha256,e.CommandSha256,e.EnvironmentSha256,e.Destination,"applied");var current=receipt;var probe=new DeploymentReceiptProbe(new Credential(),new Handler(_=>current.Status=="absent"?Json(HttpStatusCode.NotFound,new{}):Json(HttpStatusCode.OK,current)));Check((await probe.CheckAsync("one",scope,c,CancellationToken.None)).State==ExternalEffectState.Completed,"Valid receipt rejected");current=receipt with{ArtifactSha256=new string('F',64)};Check((await probe.CheckAsync("one",scope,c,CancellationToken.None)).State==ExternalEffectState.Unknown,"Stale receipt accepted");current=receipt with{Status="absent"};Check((await probe.CheckAsync("one",scope,c,CancellationToken.None)).State==ExternalEffectState.Unknown,"Missing receipt accepted");var root=Path.Combine(Path.GetTempPath(),"agentos-receipt-"+Guid.NewGuid().ToString("N"));try{var lost=false;var fake=new FakeExecutor();var transport=new Handler(_=>{if(lost)throw new IOException("response lost");return Json(HttpStatusCode.OK,receipt with{OperationId="effect"});});var journal=new EffectIntentJournal(root);var adapter=new DeploymentEffects(journal,fake,new DeploymentReceiptProbe(new Credential(),transport));var intent=await adapter.PrepareAsync("effect",scope);Check((await adapter.ExecuteAsync("effect")).State==ExternalEffectState.Prepared&&fake.Runs==0,"Deployment ran before approval");journal.Approve("effect",intent.Scope.Digest,"reviewer");lost=true;Check((await adapter.ExecuteAsync("effect")).State==ExternalEffectState.Unknown&&fake.Runs==1,"Lost receipt response was success");lost=false;Check((await adapter.ReconcileAsync("effect")).State==ExternalEffectState.Completed&&fake.Runs==1,"Receipt reconciliation replayed deployment");}finally{if(Directory.Exists(root))Directory.Delete(root,true);}}
}




